name: Gintaras Stalmokas
avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: '.NET developer with some Kubernetes and Azure infrastructure experience and a passion for game development'
# company: Company # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: Vilnius, Lithuania # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
params: {
  # layout: compact
}
social:
  email: gintaras.stalmokas@outlook.com
  github: https://github.com/GintarasDev
  linkedin: https://www.linkedin.com/in/gintarasstalmokas/
  rss: "" # Remove RSS